---
- tasks:
    - name: Install Windows updates with WinRM and reboot system
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates 
          - Tools
          - Application
          - updates
          - FeaturePacks
          - ServicePacks
        reboot: yes
        reboot_timeout: 800